View.fix
naru6117/chat-space pull request #4
Opened 2019-05-18 08:18 UTC by naru6117

## WHAT
ビュー画面（indexのみ）が正しく記述・実装できているかの確認をお願いします。

## WHY
良いchat-spaceを実装するため。

2019-05-18 08:29 UTC, i-date reviewed
ご提出ありがとうございます！コメントいたしました^^
また、実装画面を確認するため、Gyazoなどでスクショを載せていただけないでしょうか？

2019-05-18 08:29 UTC, i-date commented on app/assets/stylesheets/application.scss
> +@import "font-awesome";
最下行に空行を挿入してあげましょう。他のファイルも確認して修正しましょう。

2019-05-18 08:29 UTC, i-date commented on app/assets/stylesheets/config/reser.scss
> +/*!
_reset.scssと内容が同じでしたら削除しましょう。

2019-05-18 08:29 UTC, i-date commented on app/views/layouts/mailer.html.haml
> +!!!
mailer関連のファイルは今回使用しないので、他ファイルを含め削除しましょう。

2019-05-18 08:29 UTC, i-date commented on app/views/messages/index.html.haml
> +            メッセージ
22-48行目は繰り返し使用されるので部分テンプレートに切り出してはいかがでしょうか？

2019-05-18 08:29 UTC, i-date commented on app/views/shared/_side_bar.html.haml
> +        = link_to do
リンク先がまだ指定できない場合は以下のように#をいれてあげましょう。11行目も。
`= link_to '#' do`

2019-05-18 08:29 UTC, i-date commented on app/views/shared/_side_bar.html.haml
> +        新着メッセージ
14-28行目は繰り返し使用されるので、さらに部分テンプレートに切り出してはいかがでしょうか？

2019-05-18 08:32 UTC, naru6117 commented
> ご提出ありがとうございます！コメントいたしました^^
> また、実装画面を確認するため、Gyazoなどでスクショを載せていただけないでしょうか？

こちらです！
https://gyazo.com/39ea74d431bc4d1d0ca8de958b317255

2019-05-18 15:38 UTC, naru6117 commented on app/assets/stylesheets/application.scss
> +@import "font-awesome";
空行の挿入をしました。
他のファイルの誤字も訂正しました。
1点質問なのですが、空行を入れるとなにが変るのでしょうか。

2019-05-18 15:38 UTC, naru6117 commented on app/assets/stylesheets/config/reser.scss
> +/*!
削除しました。

2019-05-18 15:38 UTC, naru6117 commented on app/views/layouts/mailer.html.haml
> +!!!
削除しました。

2019-05-18 15:45 UTC, naru6117 commented on app/views/messages/index.html.haml
> +            メッセージ
アドバイスありがとうございます。
部分テンプレートに変更しました。

2019-05-18 15:47 UTC, naru6117 commented on app/views/shared/_side_bar.html.haml
> +        = link_to do
追加しました。

2019-05-18 16:14 UTC, naru6117 commented on app/views/shared/_side_bar.html.haml
> +        新着メッセージ
部分テンプレート化しました！

2019-05-19 02:12 UTC, kuroko918 reviewed
.

2019-05-19 02:12 UTC, kuroko918 commented on config/routes.rb
> +  resources :messages, only: [:index]
rootに指定しているので、5行目の指定は不要ですね。

2019-05-19 02:13 UTC, kuroko918 commented
あと、前回のレビューに関する変更がpushされていないので、pushしておいて下さい。

2019-05-19 23:40 UTC, naru6117 commented on config/routes.rb
> +  resources :messages, only: [:index]
削除しました

2019-05-20 08:39 UTC, naru6117 commented
> .DS_storeが上がってしまっているので、gitignoreしましょう！また、github上からも消しておいて下さい。

gitignoreしました。
github上からの削除もできていますでしょうか。

2019-05-20 08:42 UTC, miyagit commented on app/controllers/concerns/application_controller.rb
> +
ここの改行不要ですね。

2019-05-20 08:42 UTC, miyagit commented on app/controllers/concerns/messages_controller.rb
> +
こちらも不要です。

2019-05-20 08:42 UTC, miyagit commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しましょう。

2019-05-20 08:45 UTC, naru6117 commented on app/controllers/concerns/application_controller.rb
> +
改行削除しました

2019-05-20 08:46 UTC, naru6117 commented on app/controllers/concerns/messages_controller.rb
> +
削除しました

2019-05-20 09:17 UTC, naru6117 commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
修正しました

2019-05-20 09:20 UTC, i-date commented on app/views/layouts/application.html.haml
> +    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
`"http-equiv"`の後ろのハッシュロケットもシンボル型にしましょう。

2019-05-20 09:29 UTC, naru6117 commented on app/views/layouts/application.html.haml
> +    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
シンボル型に変更しました！

2019-05-20 09:32 UTC, kuroko918 requested changes
.

2019-05-20 09:32 UTC, kuroko918 commented on config/routes.rb
> +  resources :shared do
こちらのresourcesは使いますか？

2019-05-20 09:32 UTC, kuroko918 commented on app/controllers/concerns/shared_controller.rb
> +class SharedController < ApplicationController
こちらのcontrollerは今後使いますか？

2019-05-20 09:42 UTC, naru6117 commented on app/controllers/concerns/shared_controller.rb
> +class SharedController < ApplicationController
> app/assets/stylesheets/config/.DS_Store
> がまだgithub上に残ってしまっているので、消しておきましょう！

削除しました。

2019-05-20 09:48 UTC, naru6117 commented on config/routes.rb
> +  resources :shared do
使用しないので、削除しました。

2019-05-20 09:56 UTC, naru6117 commented on app/controllers/concerns/shared_controller.rb
> +class SharedController < ApplicationController
sharedのviewファイルがあるので必要だと認識しております！

2019-05-20 10:02 UTC, kuroko918 commented on app/controllers/concerns/shared_controller.rb
> +class SharedController < ApplicationController
それは全く関係ないですね！ただsharedというディレクトリに置いているだけですね。
なのでsharedディレクトリの中には部分テンプレートしかないですね。

2019-05-20 10:05 UTC, naru6117 commented on app/controllers/concerns/shared_controller.rb
> +class SharedController < ApplicationController
解説ありがとうございます！
承知しました！
こちら削除いたしました。

2019-05-20 10:08 UTC, TOMARUMARU reviewed
ファイルの最後は1行改行を入れるようにしましょう

2019-05-20 10:08 UTC, TOMARUMARU commented on config/routes.rb
> +  end
endが１つ余分ですかね

2019-05-21 01:17 UTC, naru6117 commented on config/routes.rb
> +  end
エンドを1つ消しました

2019-05-21 02:13 UTC, TOMARUMARU reviewed
ほとんどのファイルで最下行に改行が入っていないので、1行だけ入れるようにしましょう

2019-05-21 03:58 UTC, naru6117 commented
> ほとんどのファイルで最下行に改行が入っていないので、1行だけ入れるようにしましょう

追加いたしました！

2019-05-21 04:05 UTC, shingoteshima commented
lgtmです！

2019-05-21 04:53 UTC, merged